### ISSUE TITLE
Input Specification Files

### ISSUE THREAD

**Issue by LarsRhijns** [qianzhanghk/BigFuzz#11]
Hi there,

Together with a group of students from the TU Delft we are trying to extend on the BigFuzz framework. We are wondering if you could provide the input specifications for the used benchmarks in the repository? Currently there is only one in the dataset folder, namely the salary input specification. 

Thanks in advance!

**Comment by qzhang-ucr** [comment]
Hi, Thank you very much for reaching out. Please find the subjects, transformed programs, valid or invalid inputs here: https://github.com/qianzhanghk/BigFuzz-TestPrograms. Hope this helps.
